"""initial

Revision ID: 85d1cad0af6c
Revises: 
Create Date: 2026-03-06 15:28:23.294229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '85d1cad0af6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_slug'), 'sectors', ['slug'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('subsector', sa.String(length=200), nullable=True),
    sa.Column('sentiment', sa.Enum('bullish', 'neutral', 'bearish', name='sentimentenum'), nullable=True),
    sa.Column('position', sa.Enum('buy', 'hold', 'sell', 'watch', 'avoid', name='positionenum'), nullable=True),
    sa.Column('my_fair_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('upside', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('shares_out', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('free_float', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('adv_rub_mln', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p_e', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('p_bv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('gov_ownership', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('catalysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('opportunity', 'risk', 'cb_meeting', 'event', name='catalysttypeenum'), nullable=False),
    sa.Column('impact', sa.Enum('positive', 'negative', 'mixed', 'neutral', name='impactenum'), nullable=False),
    sa.Column('magnitude', sa.Enum('high', 'medium', 'low', name='magnitudeenum'), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('yield_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('announced', 'confirmed', 'paid', name='dividendstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'record_date', name='uq_dividend_company_date')
    )
    op.create_table('financial_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_type', sa.Enum('quarterly', 'yearly', 'ltm', name='periodtypeenum'), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p_e', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('p_bv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('extra_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', 'period_type', name='uq_report_company_period_type')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('impact', sa.Enum('positive', 'negative', 'mixed', 'neutral', name='impactenum'), nullable=True),
    sa.Column('strength', sa.Enum('high', 'medium', 'low', name='strengthenum'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action', sa.Enum('buy', 'hold', 'sell', name='actionenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('volume_rub', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_price_company_date')
    )
    op.create_table('trade_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('signal', sa.Enum('buy', 'skip', name='signalenum'), nullable=False),
    sa.Column('direction', sa.Enum('long-positive', 'long-oversold', 'skip', name='directionenum'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('entry_condition', sa.String(length=500), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('time_limit_days', sa.Integer(), nullable=True),
    sa.Column('expected_return_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('risk_reward', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('position_size', sa.Enum('full', 'half', 'skip', name='positionsizeenum'), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'closed', 'expired', name='signalstatusenum'), nullable=False),
    sa.Column('result_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='jobstatusenum'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_job_name'), 'job_runs', ['job_name'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('volume_rub', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'timestamp', name='uq_snapshot_company_ts')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_signals')
    op.drop_table('prices')
    op.drop_table('news')
    op.drop_table('financial_reports')
    op.drop_table('dividends')
    op.drop_table('catalysts')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_sectors_slug'), table_name='sectors')
    op.drop_table('sectors')

    for enum_name in [
        'signalstatusenum', 'positionsizeenum', 'directionenum', 'signalenum',
        'actionenum', 'strengthenum', 'impactenum', 'magnitudeenum',
        'catalysttypeenum', 'dividendstatusenum', 'periodtypeenum',
        'positionenum', 'sentimentenum',
    ]:
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
