openapi: 3.0.3
info:
  title: Trade Signals API
  version: 1.0.0
  description: |
    Схема данных для торговых сигналов на основе новостей.

    Файл `trade_signals.json` содержит сигналы, сгенерированные при анализе
    новостей о компании — стоит ли спекулятивно покупать бумагу.

    ## Как сгенерировать

    ```bash
    make news-reaction TICKER=SBER
    ```

    Или вручную: попросить Claude проанализировать новость по инструкции
    из `companies/NEWS_REACTION_GUIDE.md`.

    ## Источники данных

    - `companies/{TICKER}/data/news.json` — триггер (новость)
    - `companies/{TICKER}/_index.md` — фундаментальная оценка (fair value, sentiment)
    - `companies/{TICKER}/data/price_history.csv` — проверка «уже в цене»
    - `companies/{TICKER}/data/moex_market.json` — ликвидность (ADV)

    ## Расположение файлов

    `companies/{TICKER}/data/trade_signals.json`

components:
  schemas:
    TradeSignals:
      type: array
      description: Массив торговых сигналов (новые сверху)
      items:
        $ref: '#/components/schemas/TradeSignal'

    TradeSignal:
      type: object
      required:
        - date
        - trigger
        - signal
        - direction
        - reasoning
      properties:
        date:
          type: string
          format: date
          description: Дата анализа
          example: "2026-02-25"
        trigger:
          type: string
          description: Краткое описание новости-триггера
          example: "ФНС заблокировала счета на 223 млн ₽"
        trigger_url:
          type: string
          format: uri
          nullable: true
          description: Ссылка на новость
          example: "https://smart-lab.ru/blog/1269071.php"
        signal:
          type: string
          enum: [buy, skip]
          description: |
            Торговый сигнал:
            - `buy` — есть спекулятивная возможность
            - `skip` — не торгуем (нет возможности, высокий риск, шум)
        direction:
          type: string
          enum: [long-positive, long-oversold, skip]
          description: |
            Направление сделки:
            - `long-positive` — покупка на позитивной новости (рынок ещё не отреагировал)
            - `long-oversold` — покупка на панике (рынок перереагировал на негатив)
            - `skip` — не торгуем
        confidence:
          type: string
          enum: [high, medium, low]
          description: |
            Уверенность в сигнале:
            - `high` — risk/reward > 3, новость однозначная
            - `medium` — risk/reward 2–3, есть неопределённость
            - `low` — только для skip-сигналов
        entry:
          type: object
          nullable: true
          description: Условия входа (null для skip)
          properties:
            condition:
              type: string
              description: Описание условия входа
              example: "По рынку при открытии"
            price:
              type: number
              description: Целевая цена входа (₽)
              example: 130.0
        exit:
          type: object
          nullable: true
          description: Условия выхода (null для skip)
          properties:
            take_profit:
              type: number
              description: Цена фиксации прибыли (₽)
              example: 155.0
            stop_loss:
              type: number
              description: Цена стоп-лосса (₽)
              example: 120.0
            time_limit_days:
              type: integer
              description: Максимальный срок удержания позиции (торговых дней)
              example: 14
            exit_trigger:
              type: string
              nullable: true
              description: Событие для выхода (помимо цены)
              example: "Публикация отчёта за Q4"
        expected_return_pct:
          type: number
          nullable: true
          description: Ожидаемая доходность (%)
          example: 19.2
        risk_reward_ratio:
          type: number
          nullable: true
          description: Соотношение risk/reward (минимум 2.0 для buy)
          example: 2.5
        position_size:
          type: string
          enum: [full, half, skip]
          description: |
            Размер позиции:
            - `full` — до 5% портфеля (confidence: high)
            - `half` — до 3% портфеля (confidence: medium)
            - `skip` — не торгуем
        reasoning:
          type: string
          description: Обоснование решения (2-3 предложения)
          example: "Позитивный отчёт за Q4, рынок ещё не отреагировал (price_move +0.5%). Fair value 520 ₽ при текущей цене 317 ₽ (upside 64%). R/R = 3.2."