openapi: 3.0.3
info:
  title: Investment Trend API
  version: 1.0.0
  description: Схема данных для прогноза трендов компаний

components:
  schemas:
    CompanyTrend:
      type: object
      required:
        - ticker
        - sentiment
        - upside
        - growth_probability
        - decline_probability
        - updated
      properties:
        ticker:
          type: string
          description: Тикер компании на Московской бирже
          example: "SBER"
        sentiment:
          type: string
          enum: [bullish, neutral, bearish]
          description: Общая оценка перспектив компании
        upside:
          type: number
          format: float
          minimum: -1.0
          maximum: 10.0
          description: Потенциал роста до справедливой цены (0.64 = 64%)
          example: 0.64
        growth_probability:
          type: number
          format: float
          minimum: 0.05
          maximum: 0.90
          description: Вероятность роста цены в ближайшие 3-6 месяцев
          example: 0.70
        decline_probability:
          type: number
          format: float
          minimum: 0.05
          maximum: 0.90
          description: Вероятность падения цены в ближайшие 3-6 месяцев
          example: 0.15
        updated:
          type: string
          format: date
          description: Дата последнего расчёта
          example: "2026-01-29"
